spring:
  application:
    security:
      jwt:
        expiration: 86400000
        secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    name: reelshelf

  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/demo_db
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

tmdb:
  api:
    key: ${TMDB_API_KEY}
    base-url: https://api.themoviedb.org/3
    image-base-url: https://image.tmdb.org/t/p/w500

googlebooks:
  api:
    base-url: https://www.googleapis.com/books/v1
    key: ${GOOGLEBOOKS_API_KEY}
